version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html  # Đảm bảo Laravel ở đúng thư mục
        networks:
            - laravel_network
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:10.11
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: Qlong2003
            MYSQL_DATABASE: bookstore
            MYSQL_USER: longpham
            MYSQL_PASSWORD: Qlong2003
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: nginx_container
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html  # Chỉnh lại để đúng thư mục Laravel
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin_container
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: Qlong2003
        depends_on:
            - mariadb
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mariadb_data:
